from setuptools import setup

setup(
    name='python-code',
    version='1.0',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections',
              'venv.Lib.site-packages.mdp', 'venv.Lib.site-packages.mdp.test', 'venv.Lib.site-packages.mdp.graph',
              'venv.Lib.site-packages.mdp.hinet', 'venv.Lib.site-packages.mdp.nodes',
              'venv.Lib.site-packages.mdp.utils', 'venv.Lib.site-packages.mdp.caching',
              'venv.Lib.site-packages.mdp.parallel', 'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip.req',
              'venv.Lib.site-packages.pip.vcs', 'venv.Lib.site-packages.pip.utils', 'venv.Lib.site-packages.pip.compat',
              'venv.Lib.site-packages.pip.models', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip.commands', 'venv.Lib.site-packages.pip.operations',
              'venv.Lib.site-packages.past', 'venv.Lib.site-packages.past.tests', 'venv.Lib.site-packages.past.types',
              'venv.Lib.site-packages.past.utils', 'venv.Lib.site-packages.past.builtins',
              'venv.Lib.site-packages.past.translation', 'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.bimdp',
              'venv.Lib.site-packages.bimdp.test', 'venv.Lib.site-packages.bimdp.hinet',
              'venv.Lib.site-packages.bimdp.nodes', 'venv.Lib.site-packages.bimdp.parallel',
              'venv.Lib.site-packages.bimdp.inspection', 'venv.Lib.site-packages.numpy',
              'venv.Lib.site-packages.numpy.ma', 'venv.Lib.site-packages.numpy.ma.tests',
              'venv.Lib.site-packages.numpy.doc', 'venv.Lib.site-packages.numpy.fft',
              'venv.Lib.site-packages.numpy.fft.tests', 'venv.Lib.site-packages.numpy.lib',
              'venv.Lib.site-packages.numpy.lib.tests', 'venv.Lib.site-packages.numpy.core',
              'venv.Lib.site-packages.numpy.core.tests', 'venv.Lib.site-packages.numpy.f2py',
              'venv.Lib.site-packages.numpy.f2py.tests', 'venv.Lib.site-packages.numpy.tests',
              'venv.Lib.site-packages.numpy.compat', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing.nose_tools',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.scipy', 'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.sparse', 'venv.Lib.site-packages.scipy.sparse.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg', 'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.tool',
              'venv.Lib.site-packages.wheel.signatures', 'venv.Lib.site-packages.future',
              'venv.Lib.site-packages.future.moves', 'venv.Lib.site-packages.future.moves.dbm',
              'venv.Lib.site-packages.future.moves.html', 'venv.Lib.site-packages.future.moves.http',
              'venv.Lib.site-packages.future.moves.test', 'venv.Lib.site-packages.future.moves.urllib',
              'venv.Lib.site-packages.future.moves.xmlrpc', 'venv.Lib.site-packages.future.moves.tkinter',
              'venv.Lib.site-packages.future.tests', 'venv.Lib.site-packages.future.types',
              'venv.Lib.site-packages.future.utils', 'venv.Lib.site-packages.future.builtins',
              'venv.Lib.site-packages.future.backports', 'venv.Lib.site-packages.future.backports.html',
              'venv.Lib.site-packages.future.backports.http', 'venv.Lib.site-packages.future.backports.test',
              'venv.Lib.site-packages.future.backports.email', 'venv.Lib.site-packages.future.backports.email.mime',
              'venv.Lib.site-packages.future.backports.urllib', 'venv.Lib.site-packages.future.backports.xmlrpc',
              'venv.Lib.site-packages.future.standard_library', 'venv.Lib.site-packages.kohonen',
              'venv.Lib.site-packages.sklearn', 'venv.Lib.site-packages.sklearn.svm',
              'venv.Lib.site-packages.sklearn.svm.tests', 'venv.Lib.site-packages.sklearn.tree',
              'venv.Lib.site-packages.sklearn.tree.tests', 'venv.Lib.site-packages.sklearn.tests',
              'venv.Lib.site-packages.sklearn.utils', 'venv.Lib.site-packages.sklearn.utils.tests',
              'venv.Lib.site-packages.sklearn.utils.sparsetools',
              'venv.Lib.site-packages.sklearn.utils.sparsetools.tests', 'venv.Lib.site-packages.sklearn.cluster',
              'venv.Lib.site-packages.sklearn.cluster.tests', 'venv.Lib.site-packages.sklearn.metrics',
              'venv.Lib.site-packages.sklearn.metrics.tests', 'venv.Lib.site-packages.sklearn.metrics.cluster',
              'venv.Lib.site-packages.sklearn.metrics.cluster.tests', 'venv.Lib.site-packages.sklearn.mixture',
              'venv.Lib.site-packages.sklearn.mixture.tests', 'venv.Lib.site-packages.sklearn.datasets',
              'venv.Lib.site-packages.sklearn.datasets.tests', 'venv.Lib.site-packages.sklearn.ensemble',
              'venv.Lib.site-packages.sklearn.ensemble.tests', 'venv.Lib.site-packages.sklearn.manifold',
              'venv.Lib.site-packages.sklearn.manifold.tests', 'venv.Lib.site-packages.sklearn.externals',
              'venv.Lib.site-packages.sklearn.externals.joblib', 'venv.Lib.site-packages.sklearn.neighbors',
              'venv.Lib.site-packages.sklearn.neighbors.tests', 'venv.Lib.site-packages.sklearn.covariance',
              'venv.Lib.site-packages.sklearn.covariance.tests', 'venv.Lib.site-packages.sklearn._build_utils',
              'venv.Lib.site-packages.sklearn.linear_model', 'venv.Lib.site-packages.sklearn.linear_model.tests',
              'venv.Lib.site-packages.sklearn.__check_build', 'venv.Lib.site-packages.sklearn.decomposition',
              'venv.Lib.site-packages.sklearn.decomposition.tests', 'venv.Lib.site-packages.sklearn.preprocessing',
              'venv.Lib.site-packages.sklearn.preprocessing.tests', 'venv.Lib.site-packages.sklearn.neural_network',
              'venv.Lib.site-packages.sklearn.neural_network.tests', 'venv.Lib.site-packages.sklearn.model_selection',
              'venv.Lib.site-packages.sklearn.model_selection.tests', 'venv.Lib.site-packages.sklearn.semi_supervised',
              'venv.Lib.site-packages.sklearn.semi_supervised.tests', 'venv.Lib.site-packages.sklearn.gaussian_process',
              'venv.Lib.site-packages.sklearn.gaussian_process.tests',
              'venv.Lib.site-packages.sklearn.feature_selection',
              'venv.Lib.site-packages.sklearn.feature_selection.tests',
              'venv.Lib.site-packages.sklearn.feature_extraction',
              'venv.Lib.site-packages.sklearn.feature_extraction.tests',
              'venv.Lib.site-packages.sklearn.cross_decomposition',
              'venv.Lib.site-packages.sklearn.cross_decomposition.tests', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.matplotlib',
              'venv.Lib.site-packages.matplotlib.tri', 'venv.Lib.site-packages.matplotlib.axes',
              'venv.Lib.site-packages.matplotlib.cbook', 'venv.Lib.site-packages.matplotlib.style',
              'venv.Lib.site-packages.matplotlib.compat', 'venv.Lib.site-packages.matplotlib.testing',
              'venv.Lib.site-packages.matplotlib.testing._nose',
              'venv.Lib.site-packages.matplotlib.testing._nose.plugins',
              'venv.Lib.site-packages.matplotlib.testing.jpl_units', 'venv.Lib.site-packages.matplotlib.backends',
              'venv.Lib.site-packages.matplotlib.backends.qt_editor', 'venv.Lib.site-packages.matplotlib.sphinxext',
              'venv.Lib.site-packages.matplotlib.projections', 'venv.Lib.site-packages.setuptools',
              'venv.Lib.site-packages.setuptools.extern', 'venv.Lib.site-packages.setuptools.command',
              'venv.Lib.site-packages.libfuturize', 'venv.Lib.site-packages.libfuturize.fixes',
              'venv.Lib.site-packages.mpl_toolkits.mplot3d', 'venv.Lib.site-packages.mpl_toolkits.axes_grid',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid1', 'venv.Lib.site-packages.mpl_toolkits.axisartist',
              'venv.Lib.site-packages.libpasteurize', 'venv.Lib.site-packages.libpasteurize.fixes',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Damien Billot-Mornet',
    author_email='damien.billot-mornet@fanuc.eu',
    description=''
)